### ISSUE TITLE
loneicewolf secret

### ISSUE THREAD

**Issue by dfalt0** [loneicewolf/loneicewolf#1]
hallo

found your secret - ive been browsing github for a few hours, i barely add anything to it and would like to start to work on things and add them to my profile

came across your profile when searching for... someting idk
first i found this [(https://github.com/alexandreborges/malwoverview)]
then went through profiles and repos
came across this profile - https://github.com/RamadhanAmizudin
searched "ios security"
looked through a few others
and i dont remember how i got to your profile no idea lol '>.>

but im here bc i found your secret in your README when trying to make my own

:D

**Comment by loneicewolf** [comment]
# @dfalt0  Heh, Congratz! You're the first one `^_^`

**Comment by loneicewolf** [comment]
was wondering when someone or some`thing` would detect it, but here you popped up!

**Comment by loneicewolf** [comment]
# @dfalt0  Heh, Congratz! You're the first one `^_^` 
was wondering when someone or some`thing` would detect it, but here you popped up!

>  came across this profile - https://github.com/RamadhanAmizudin
searched "ios security"
looked through a few others
and i dont remember how i got to your profile no idea lol '>.>

__..Perhaps trough the  [RamadhanAmizudin's malware repo](https://github.com/RamadhanAmizudin/malware)? I added [fanny.bmp](https://github.com/loneicewolf/fanny.bmp) there :-)__

![image](https://github.com/loneicewolf/loneicewolf/assets/68499986/01713570-031b-419d-b339-025a9cf428d0)

Next 'easter egg' or 'secret' I will do will probably be about cryptography or steganography, ofc it will not be totally obvious but not totally the opposite either, anyway! thanks for pointing it out :)


## Wishes from Sweden! ❤️  Always nice to see others into infosec!

**Comment by loneicewolf** [comment]
# also just for those who wondering: 
![image](https://github.com/loneicewolf/loneicewolf/assets/68499986/356fd37f-1397-4c8b-b7af-49c01296184a)
 this is what this conversation is about `;)`

**Comment by dfalt0** [comment]
ayoo thanks thats prob how i found you yea lol 
nice meeting you <3

**Comment by dfalt0** [comment]
ill try to find the next one when it's around ;3

**Comment by loneicewolf** [comment]
> ill try to find the next one when it's around ;3

Heh, good luck! I always paste a clue in my readme so people don't look when I don't have anything to look for, but well!  Yeah ^_^ feel free to dm in discord if you want, if you have discord of course, other than that I wish you a amazing weekend!
